********************************************************************************
* SPICE netlist generated by HiPer Verify's NetList Extractor
*
* Extract Date/Time:	Mon Dec 22 15:34:07 2025
* L-Edit Version:		L-Edit Win64 16.30.20150626.05:33:01
*
* Rule Set Name:		
* TDB File Name:		D:\BaiduNetdiskDownload\tanner1\Dsuocun\LAYOUT\lib.defs
* PX Command File:	
* Command File:		D:\BaiduNetdiskDownload\tanner1\Dsuocun\LAYOUT\lights.ext
* Cell Name:			Dsuocun
* Write Flat:			NO
********************************************************************************


.model NMOS
.model PMOS

****************************************
.SUBCKT 2shuru 1 2 3 4 6
MU27/1 3 1 2 2 PMOS l=2e-006 w=5e-006  $ (30.5 21.5 32.5 26.5)
MU29/1 5 1 4 4 NMOS l=2e-006 w=5e-006  $ (30.5 -8.5 32.5 -3.5)
MU28/1 2 6 3 2 PMOS l=2e-006 w=5e-006  $ (38.5 21.5 40.5 26.5)
MU30/1 3 6 5 4 NMOS l=2e-006 w=5e-006  $ (38.5 -8.5 40.5 -3.5)
* Device count
* MU27/(PMOS)		1
* MU28/(PMOS)		1
* MU29/(NMOS)		1
* MU30/(NMOS)		1
* Number of devices:	4
* Number of nodes:	6
.ENDS

****************************************
.SUBCKT INV 1 2 3 4
MU22/1 3 1 2 2 NMOS l=2e-006 w=5e-006  $ (30.5 0 32.5 5)
MU21/1 3 1 4 4 PMOS l=2e-006 w=5e-006  $ (30.5 22 32.5 27)
* Device count
* MU21/(PMOS)		1
* MU22/(NMOS)		1
* Number of devices:	2
* Number of nodes:	4
.ENDS

****************************************

XU41 1 Vdd NQ Gnd_ Q 2shuru  $ (155 -1 219 49) $T=197 -4.5 0 270 1
XU38 NQ Vdd Q Gnd_ 2 2shuru  $ (155 90 219 140) $T=197 86.5 0 270 1
XU40 3 Vdd 1 Gnd_ CLK 2shuru  $ (61.5 -2.5 125.5 47.5) $T=103.5 -6 0 270 1
XU39 CLK Vdd 2 Gnd_ D 2shuru  $ (61.5 94 125.5 144) $T=103.5 90.5 0 270 1
XU37 D Gnd_ 3 Vdd INV  $ (-16.5 -7 22.5 52.5) $T=-21 7.5 0 0 1
* Top level device count
* Number of devices:	0
* Number of nodes:	9


* Cumulative device count
* MU21/(PMOS)		1
* MU22/(NMOS)		1
* MU27/(PMOS)		4
* MU28/(PMOS)		4
* MU29/(NMOS)		4
* MU30/(NMOS)		4
* Number of devices:	18
* Number of nodes:	13
