********************************************************************************
* SPICE netlist generated by HiPer Verify's NetList Extractor
*
* Extract Date/Time:	Mon Dec 22 11:21:50 2025
* L-Edit Version:		L-Edit Win64 16.30.20150626.05:33:01
*
* Rule Set Name:		
* TDB File Name:		D:\BaiduNetdiskDownload\tanner1\NAND2\LAYOUT\2shuyuyufeimen\lib.defs
* PX Command File:	
* Command File:		D:\BaiduNetdiskDownload\tanner1\NAND2\LAYOUT\2shuyuyufeimen\lights.ext
* Cell Name:			NAND2
* Write Flat:			NO
********************************************************************************


.model NMOS
.model PMOS

****************************************

MU13/1 Out A Vdd Vdd PMOS l=2e-006 w=5e-006  $ (9.5 31 11.5 36)
MU12/1 1 A Gnd_ Gnd_ NMOS l=2e-006 w=5e-006  $ (9.5 -1.5 11.5 3.5)
MU15/1 Vdd B Out Vdd PMOS l=2e-006 w=5e-006  $ (17.5 31 19.5 36)
MU16/1 Out B 1 Gnd_ NMOS l=2e-006 w=5e-006  $ (17.5 -1.5 19.5 3.5)
* Top level device count
* MU12/(NMOS)		1
* MU13/(PMOS)		1
* MU15/(PMOS)		1
* MU16/(NMOS)		1
* Number of devices:	4
* Number of nodes:	6


* Cumulative device count
* MU12/(NMOS)		1
* MU13/(PMOS)		1
* MU15/(PMOS)		1
* MU16/(NMOS)		1
* Number of devices:	4
* Number of nodes:	6
