********************************************************************************
* SPICE netlist generated by HiPer Verify's NetList Extractor
*
* Extract Date/Time:	Mon Dec 22 16:29:52 2025
* L-Edit Version:		L-Edit Win64 16.30.20150626.05:33:01
*
* Rule Set Name:		
* TDB File Name:		D:\BaiduNetdiskDownload\tanner1\NAND3\LAYOUT\lib.defs
* PX Command File:	
* Command File:		D:\BaiduNetdiskDownload\tanner1\NAND3\LAYOUT\lights.ext
* Cell Name:			DAND3
* Write Flat:			NO
********************************************************************************


.model NMOS
.model PMOS

****************************************
.SUBCKT PMOS_pseudo_1 1 2 3
M1 3 1 2 3 PMOS l=2e-006 w=5e-006  $ (-1 -2.5 1 2.5)
* Device count
* M(PMOS)		1
* Number of devices:	1
* Number of nodes:	3
.ENDS

****************************************
.SUBCKT PMOS_pseudo_2 1 2 3 4
M1 3 1 2 4 PMOS l=2e-006 w=5e-006  $ (-1 -2.5 1 2.5)
* Device count
* M(PMOS)		1
* Number of devices:	1
* Number of nodes:	4
.ENDS

****************************************

MU49/1 Out C 1 GND_ NMOS l=2e-006 w=5e-006  $ (46.5 -13 48.5 -8)
MU48/1 1 2 3 GND_ NMOS l=2e-006 w=5e-006  $ (38.5 -13 40.5 -8)
MU46/1 Out C Vdd Vdd PMOS l=2e-006 w=5e-006  $ (46.5 21.5 48.5 26.5)
MU43/1 3 A GND_ GND_ NMOS l=2e-006 w=5e-006  $ (30.5 -13 32.5 -8)
XU45 2 Out Vdd PMOS_pseudo_1  $ (27.5 16.5 51.5 31.5) $T=39.5 24 0 0 1
XU42 A Vdd Out Vdd PMOS_pseudo_2  $ (19.5 16.5 43.5 31.5) $T=31.5 24 0 0 1
* Top level device count
* MU43/(NMOS)		1
* MU46/(PMOS)		1
* MU48/(NMOS)		1
* MU49/(NMOS)		1
* Number of devices:	4
* Number of nodes:	8


* Cumulative device count
* M(PMOS)		2
* MU43/(NMOS)		1
* MU46/(PMOS)		1
* MU48/(NMOS)		1
* MU49/(NMOS)		1
* Number of devices:	6
* Number of nodes:	8
